# -*- coding: utf-8 -*-

WS_NFSE_CONSULTAR_SIT_LOTE_RPS  = 0
WS_NFSE_CONSULTAR_NFSE_POR_RPS = 1
WS_NFSE_RECEPCIONAR_LOTE_RPS   = 2
WS_NFSE_CONSULTAR_LOTE_RPS     = 3
WS_NFSE_GERAR_NFSE             = 4
WS_NFSE_CONSULTAR_NFSE         = 5
WS_NFSE_CANCELAR_NFSE          = 6

NFSE_AMBIENTE_PRODUCAO = 1
NFSE_AMBIENTE_HOMOLOGACAO = 2